name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  FTP_URL: ${{ secrets.FTP_PUBLICACAO }}
  FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
  FTP_SENHA: ${{ secrets.FTP_SENHA }}
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: FTP
      #uses: airvzxf/ftp-deployment-action@latest
      #with:
        #server: ${{ secrets.FTP_PUBLICACAO }}
        #user: ${{ secrets.FTP_USUARIO }}
        #password: ${{ secrets.FTP_SENHA }}
        #local_dir: ./
        #delete: true
        #ftp_ssl_allow: true
    - name: FTP Deploy
  # You may pin to the exact commit or the version.
  # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ${{ secrets.FTP_PUBLICACAO }}
        # ftp username
        username: ${{ secrets.FTP_USUARIO }}
        # ftp password
        password: ${{ secrets.FTP_SENHA }}
        # Server port to connect to (read your web hosts docs)
        port: 21
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        # Folder to upload from, must end with trailing slash /
        local-dir: /
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: /
        # Path and name of the state file - this file is used to track which files have been deployed
        #state-name: # optional
        # Prints which modifications will be made with current config options, but doesnt actually make any changes
        #dry-run: # optional
        # Deletes ALL contents of server-dir, even items in excluded with exclude argument
        dangerous-clean-slate: true
        # An array of glob patterns, these files will not be included in the publish/delete process
        #exclude: # optional
        # How verbose should the information be - warn, info, debug
        log-level: info
        # strict or loose
        security: strict
